// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB78Sw-qKrhCwtzlwfUjOxXo5Xh-ZGX488',
    appId: '1:433652238558:web:23a0a0d5c75f29a8451a4f',
    messagingSenderId: '433652238558',
    projectId: 'futbox-project',
    authDomain: 'futbox-project.firebaseapp.com',
    storageBucket: 'futbox-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl_x16Vk8CnMAyb9PnRe8ZZ1w-r_abD7s',
    appId: '1:433652238558:android:9da735d287becf16451a4f',
    messagingSenderId: '433652238558',
    projectId: 'futbox-project',
    storageBucket: 'futbox-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWqfhfhA8ewo-rdncFML87i7Co5CDbF5k',
    appId: '1:433652238558:ios:ca69c34f958d50db451a4f',
    messagingSenderId: '433652238558',
    projectId: 'futbox-project',
    storageBucket: 'futbox-project.firebasestorage.app',
    iosBundleId: 'com.example.futboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWqfhfhA8ewo-rdncFML87i7Co5CDbF5k',
    appId: '1:433652238558:ios:ca69c34f958d50db451a4f',
    messagingSenderId: '433652238558',
    projectId: 'futbox-project',
    storageBucket: 'futbox-project.firebasestorage.app',
    iosBundleId: 'com.example.futboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB78Sw-qKrhCwtzlwfUjOxXo5Xh-ZGX488',
    appId: '1:433652238558:web:6a66cdd1b195c958451a4f',
    messagingSenderId: '433652238558',
    projectId: 'futbox-project',
    authDomain: 'futbox-project.firebaseapp.com',
    storageBucket: 'futbox-project.firebasestorage.app',
  );
}
